name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
  encryptionKey:
    required: true
    description: Gradle cache encryption key
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 25
        check-latest: true
    - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      with:
        cache-encryption-key: ${{ inputs.encryptionKey }}
    - uses: testlens-app/setup-testlens@aa97c5917d05d7cd6aec289d31fc790935924d59 # v1.5.1
    - shell: bash
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      run: | # zizmor: ignore[template-injection]
        ./gradlew \
        -Dorg.gradle.java.installations.auto-download=false \
        -Pjunit.develocity.predictiveTestSelection.enabled=true \
        -Pjunit.develocity.predictiveTestSelection.selectRemainingTests=${{ github.event_name != 'pull_request' }} \
        "-Dscan.value.GitHub job=${{ github.job }}" \
        javaToolchains \
        ${{ inputs.arguments }}
