name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
  encryptionKey:
    required: true
    description: Gradle cache encryption key
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 25
        check-latest: true
    - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
      with:
        cache-encryption-key: ${{ inputs.encryptionKey }}
    - uses: testlens-app/setup-testlens@304aa0888a2485ef4135a55d6eb7352e0714a2c1 # v1.7.0
    - shell: bash
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      run: | # zizmor: ignore[template-injection]
        ./gradlew \
        -Dorg.gradle.java.installations.auto-download=false \
        -Pjunit.develocity.buildCache.pushEnabled=${{ github.repository == 'junit-team/junit-framework' }} \
        -Pjunit.develocity.predictiveTestSelection.enabled=true \
        -Pjunit.develocity.predictiveTestSelection.selectRemainingTests=${{ github.event_name != 'pull_request' }} \
        "-Dscan.value.GitHub job=${{ github.job }}" \
        javaToolchains \
        ${{ inputs.arguments }}
