comment: false

coverage:
  status:
    project:
      default:
        threshold: "1"
        informational: true
    patch:
      default:
        target: auto
        # Do not allow coverage to decrease 
        threshold: 0
        only_pulls: true

codecov:
  max_report_age: off
