[[release-notes-6.0.0]]
== 6.0.0

*Date of Release:* ❓

*Scope:*

* Java 17 and Kotlin 2.2 baseline
* Single version number for Platform, Jupiter, and Vintage
* Use of JSpecify annotations to document nullability
* Integration of JFR functionality into `junit-platform-launcher`
* Removal of `junit-platform-runner` and `junit-platform-jfr`
* Switch to FastCSV library for `@CsvSource` and `@CsvFileSource`
* Support for using Kotlin `suspend` functions as test methods
* Support for cancelling test execution via `CancellationToken`
* New `--fail-fast` mode for ConsoleLauncher
* Deterministic order of `@Nested` classes
* Inheritance of `@TestMethodOrder` by enclosed `@Nested` classes
* `MethodOrderer.Default` and `ClassOrderer.Default` for `@Nested` classes
* Removal of various deprecated behaviors and APIs


For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/87?closed=1+[6.0.0-M1],
link:{junit-framework-repo}+/milestone/99?closed=1+[6.0.0-M2],
link:{junit-framework-repo}+/milestone/102?closed=1+[6.0.0-RC1],
link:{junit-framework-repo}+/milestone/105?closed=1+[6.0.0-RC2],
link:{junit-framework-repo}+/milestone/106?closed=1+[6.0.0-RC3], and
link:{junit-framework-repo}+/milestone/103?closed=1+[6.0.0]
milestone pages in the JUnit repository on GitHub.

[TIP]
.Migration Guide
====
Please refer to the
https://github.com/junit-team/junit-framework/wiki/Upgrading-to-JUnit-6.0[wiki] for
guidance on upgrading from JUnit 5.x.y to 6.0.0.
====


[[release-notes-6.0.0-overall-improvements]]
=== Overall Improvements

[[release-notes-6.0.0-overall-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* Minimum required Java version is now 17.
* Minimum required Kotlin version is now 2.2.
* Platform artifacts now use the same version number as Jupiter and Vintage artifacts.

[[release-notes-6.0.0-overall-new-features-and-improvements]]
==== New Features and Improvements

* All JUnit modules now use https://jspecify.dev/[JSpecify] nullability annotations to
  indicate which method parameters, return types, etc. can be `null`.


[[release-notes-6.0.0-junit-platform]]
=== JUnit Platform

[[release-notes-6.0.0-junit-platform-bug-fixes]]
==== Bug Fixes

* The `Launcher` (specifically `LauncherDiscoveryResult`) now retains the original
  `TestEngine` registration order after pruning test engines without tests, thereby
  ensuring reliable test execution order of multiple test engines.

[[release-notes-6.0.0-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* Remove deprecated support for running the `ConsoleLauncher` without specifying a
  subcommand.
* Remove support for deprecated non-conventional `ConsoleLauncher` options such as
  `--h` (rather than `-h`) or `-help` (rather than `--help`).
* The `junit-platform-runner` module that provided the JUnit 4 based `JUnitPlatform`
  runner has been discontinued.
* The `junit-platform-jfr` module that provided custom Java Flight Recorder (JFR) events
  for test discovery and execution has been discontinued. Instead, the functionality is
  now available directly in `junit-platform-launcher` without requiring an additional
  dependency.
* Support for Maven Surefire/Failsafe versions less than 3.0.0 has been dropped.
* The following deprecated APIs have been removed:
  - `ReflectionSupport.loadClass(String)` method
  - `ReflectionUtils.readFieldValue(...)` methods
  - `ReflectionUtils.getMethod(...)` method
  - `BlacklistedExceptions` class
  - `PreconditionViolationException` class (from `org.junit.platform.commons.util`)
  - `ClasspathScanningSupport` class
  - `ConfigurationParameters.size()` method
  - `MethodSelector.getMethodParameterTypes()` method
  - `NestedMethodSelector.getMethodParameterTypes()` method
  - `ReportEntry()` constructor
  - `SingleTestExecutor` class
  - `LauncherDiscoveryRequestBuilder()` constructor
  - `LegacyReportingUtils` class
  - `TestPlan.add(TestIdentifier)`, `TestPlan.getChildren(String)`, and
    `TestPlan.getTestIdentifier(String)` methods
  - `TestPlan.add(TestIdentifier)` and `TestPlan.getChildren(String)` methods
  - `@UseTechnicalNames` annotation
  - `EngineTestKit.execute(String, EngineDiscoveryRequest)`,
    `EngineTestKit.execute(TestEngine, EngineDiscoveryRequest)`, and
    `EngineTestKit.Builder.filters(...)` methods
* Support for "legacy semantics" for field and method searches that used to be
  configurable via the `junit.platform.reflection.search.useLegacySemantics` system
  property has been removed. JUnit now always adheres to standard Java semantics regarding
  whether a given field or method is visible or overridden according to the rules of the
  Java language.
* The type bounds of the following methods have been changed to be more flexible and allow
  nullable and non-nullable types:
  - `ConfigurationParameters.get(String, Function)`
  - `NamespacedHierarchicalStore.getOrComputeIfAbsent(N, K, Function)`
  - `NamespacedHierarchicalStore.getOrComputeIfAbsent(N, K, Function, Class)`
* Discontinue `junit-platform-suite-commons` which is now integrated into
  `junit-platform-suite`.
* Deprecate `Launcher.execute(TestPlan, TestExecutionListener[])` and
  `Launcher.execute(LauncherDiscoveryRequest, TestExecutionListener[])` in favor of
  `Launcher.execute(LauncherExecutionRequest)`
* `ConversionSupport` now converts `String` to `Locale` using the IETF BCP 47 language tag
  format supported by the `Locale.forLanguageTag(String)` factory method instead of the
  format used by the deprecated `Locale(String)` constructor.
* Deprecate `getOrComputeIfAbsent(...)` methods in `NamespacedHierarchicalStore` in favor
  of the new `computeIfAbsent(...)` methods.
* Setting an invalid value for one of the following enum-based configuration parameters
  now causes test discovery to fail:
  - `junit.platform.discovery.issue.failure.phase`
  - `junit.platform.discovery.issue.severity.critical`
* The methods `findNestedClasses` and `streamNestedClasses` in `ReflectionSupport` now
  return nested classes declared in the same enclosing class or interface ordered in a
  deterministic but intentionally nonobvious way.
* Serialization support for `TestIdentifier` has been changed in a backwards-incompatible
  way in order to simplify the implementation.
* Deprecate `OutputDirectoryProvider` interface in favor of the new
  `OutputDirectoryCreator` interface to resolve cyclic package dependency along
  with the following APIs (which all have replacements working with
  `OutputDirectoryCreator`):
  - `EngineDiscoveryRequest.getOutputDirectoryProvider()`
  - `ExecutionRequest.getOutputDirectoryProvider()`
  - `LauncherDiscoveryRequestBuilder.outputDirectoryProvider(OutputDirectoryProvider)`
  - `TestPlan.getOutputDirectoryProvider()`
  - `EngineTestKit.Builder.outputDirectoryProvider(OutputDirectoryProvider)`
* Deprecate `org.junit.platform.commons.support.Resource` interface in favor of the new
  `org.junit.platform.commons.io.Resource` one.
* Deprecate `Resource`-related methods in `ReflectionSupport` in favor of corresponding
  methods in new `ResourceSupport` class:
  - `findAllResourcesInClasspathRoot(URI, Predicate)`
  - `findAllResourcesInModule(String, Predicate)`
  - `findAllResourcesInPackage(String, Predicate)`
  - `streamAllResourcesInClasspathRoot(URI, Predicate)`
  - `streamAllResourcesInModule(String, Predicate)`
  - `streamAllResourcesInPackage(String, Predicate)`
  - `tryToGetResources(String)`
  - `tryToGetResources(String, ClassLoader)`
* Deprecate `DiscoverySelectors.selectClasspathResource(Set)` method in favor of
  `selectClasspathResourceByName(Set)`.
* Deprecate `ClasspathResourceSelector.getClasspathResources()` method in favor of
  `getResources()`.
* Deprecate
  `EngineDiscoveryRequestResolver.Builder.addResourceContainerSelectorResolver(Predicate)`
  method in favor of `addResourceContainerSelectorResolver(ResourceFilter)`.
* Deprecate `Resource`-related methods in `ClasspathScanner` in favor of new methods using
  `org.junit.platform.commons.io.Resource` and `ResourceFilter`:
  - `scanForResourcesInPackage(String, Predicate)`
  - `scanForResourcesInClasspathRoot(URI, Predicate)`

[[release-notes-6.0.0-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Introduce new `Launcher.execute({LauncherExecutionRequest})` API with corresponding
  `LauncherExecutionRequestBuilder` to enable the addition of parameters to test
  executions without additional overloads of `execute(...)`.
* Introduce `LauncherDiscoveryRequestBuilder.forExecution()` method as a convenience
  method for constructing a `{LauncherExecutionRequest}` that contains a
  `{LauncherDiscoveryRequest}`.
* Introduce support for cancelling a running test execution via a `{CancellationToken}`
  passed to the `{Launcher}` as part of a `{LauncherExecutionRequest}` and from there to
  all registered test engines. Please refer to the
  <<../user-guide/index.adoc#launcher-api-launcher-cancellation, User Guide>> for details
  and a usage example.
* Passing the `--fail-fast` option to the `execute` subcommand of the `ConsoleLauncher`
  now causes test execution to be cancelled after the first failed test.
* Provide cancellation support for implementations of `{HierarchicalTestEngine}` such as
  JUnit Jupiter, Spock, and Cucumber.
* Provide cancellation support for the `@Suite` test engine.
* Introduce `TestTask.getTestDescriptor()` method for use in
  `HierarchicalTestExecutorService` implementations.
* Introduce `computeIfAbsent(...)` methods in `NamespacedHierarchicalStore` to simplify
  working with non-nullable types.
* Stack traces are now pruned up to the test method or lifecycle method.
* Convention-based conversion in `ConversionSupport` now supports factory methods and
  factory constructors that accept a single `CharSequence` argument in addition to the
  existing support for factories that accept a single `String` argument.
* Non-printable control characters in display names are now replaced with alternative
  representations. For example, `\n` is replaced with `<LF>`. This applies to all display
  names in JUnit Jupiter, `@SuiteDisplayName`, and any other test engines that subclass
  `AbstractTestDescriptor`. Please refer to the
  <<../user-guide/index.adoc#writing-tests-display-names, User Guide>> for details.
* To help diagnosing potentially invalid invocations, the Console Launcher now logs
  warnings for nonexistent classpath roots added via `--classpath` or `--scan-classpath`
  rather than silently ignoring them.
* The `execute(TestPlan,{nbsp}TestExecutionListener...)` and
  `execute(LauncherDiscoveryRequest,{nbsp}TestExecutionListener...)` methods in the
  `Launcher` API are no longer deprecated.
* New `discoveryRequest()` method in `{LauncherDiscoveryRequestBuilder}`, which is an
  alias for the existing `request()` method and is intended to be used via a `static`
  import.
* New `executionRequest(...)` methods in `{LauncherExecutionRequestBuilder}`, which are
  aliases for the existing `request(...)` methods and are intended to be used via a
  `static` import.
* New `selectClasses(...)` and `selectClassesByName(...)` factory methods have been
  introduced in `{DiscoverySelectors}` to simplify use cases where one needs to select
  multiple individual test classes for the `Launcher` or `EngineTestKit`.
* New `selectors(List)` builder method for `{EngineTestKit}` which can be used in
  conjunction with the new `selectClasses(...)` and `selectClassesByName(...)` factory
  methods in `DiscoverySelectors`.
* New classpath resource abstraction in `org.junit.platform.commons.io.Resource` with
  support for loading resources or finding them on the classpath via static utility
  methods in the new `org.junit.platform.commons.support.ResourceSupport` class.
* New `FileSource.withPosition(FilePosition)` method to avoid the overhead of redundant
  canonicalization of files when using `FileSource.from(File, FilePosition)` with many
  different `FilePosition` instances for the same `File`.


[[release-notes-6.0.0-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-6.0.0-junit-jupiter-bug-fixes]]
==== Bug Fixes

* CSV headers are now properly supported with the default display name pattern and the
  explicit `+{argumentsWithNames}+` display name pattern for parameterized tests that
  utilize the `useHeadersInDisplayName` flag in `@CsvSource` and `@CsvFileSource`.
  Specifically, the parameter name is no longer duplicated in the display name when a CSV
  header is desired instead.

[[release-notes-6.0.0-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* The following deprecated APIs have been removed:
  - `MethodOrderer.Alphanumeric` class
  - `InvocationInterceptor.interceptDynamicTest(Invocation, ExtensionContext)` method
* The deprecated `junit.jupiter.tempdir.scope` configuration parameter is no longer
  supported.
* The `JRE` enum constants for `JAVA_8` to `JAVA_16` have been deprecated because they can
  no longer be used at runtime since `JAVA_17` is the new baseline. Please also manually
  update any values used with the `minVersion` and `maxVersion` attributes in
  `@EnabledForJreRange` and `@DisabledForJreRange` or the `versions` attributes in
  `@EnabledOnJre` and `@DisabledOnJre` to ensure that you are no longer declaring version
  values less than 17.
* `@EnabledForJreRange` and `@DisabledForJreRange` now use `JAVA_17` as their default
  `min` value.
* The contracts for the `Executable` parameters of Kotlin-specific `assertTimeout`
  functions were changed from `callsInPlace(executable, EXACTLY_ONCE)` to
  `callsInPlace(executable, AT_MOST_ONCE)` which might result in compilation errors.
* As a result of migrating from
  https://github.com/uniVocity/univocity-parsers[univocity-parsers] to
  https://fastcsv.org/[FastCSV] for `@CsvSource` and `@CsvFileSource`, root causes and
  messages of exceptions thrown for malformed CSV input may differ in some cases. While
  the overall parsing behavior remains consistent, this may affect custom error handling
  that relies on specific exception types or messages.
* The `lineSeparator` attribute in `@CsvFileSource` has been removed. The line separator
  is now automatically detected, meaning that any of `\r`, `\n`, or `\r\n` is treated as a
  line separator.
* Attributes such as `ignoreLeadingAndTrailingWhitespace`, `nullValues`, and others in
  `@CsvSource` and `@CsvFileSource` now apply to header fields as well as to regular
  fields.
* Extra characters after a closing quote are no longer allowed in `@CsvSource` and
  `@CsvFileSource`. For example, if a single quote is used as the quote character,
  the following CSV value `'foo'INVALID,'bar'` will now cause an exception to be thrown.
  This helps ensure that malformed input is not silently accepted or misinterpreted.
* The `junit-jupiter-migrationsupport` artifact and its contained classes are now
  deprecated and will be removed in the next major version.
* The type bounds of the following methods have been changed to be more flexible and allow
  nullable and non-nullable types:
  - `ExtensionContext.getConfigurationParameter(String, Function)`
  - `ExtensionContext.getOrComputeIfAbsent(K, Function)`
  - `ExtensionContext.getOrComputeIfAbsent(K, Function, Class)`
* Change the return type of the `provideTestTemplateInvocationContexts(ExtensionContext)`
  method in the `TestTemplateInvocationContextProvider` interface from
  `Stream<TestTemplateInvocationContext>` to
  `Stream<? extends TestTemplateInvocationContext>`.
* Remove support for the `junit.jupiter.params.arguments.conversion.locale.format`
  configuration parameter. `Locale` conversions are now always performed using the IETF
  BCP 47 language tag format supported by the `Locale.forLanguageTag(String)` factory
  method.
* Deprecate `getOrComputeIfAbsent(...)` methods in `ExtensionContext.Store` in favor of
  the new `computeIfAbsent(...)` methods.
* Setting an invalid value for one of the following enum-based configuration parameters
  now causes test discovery or execution to fail:
  - `junit.jupiter.execution.parallel.mode.default`
  - `junit.jupiter.execution.parallel.mode.classes.default`
  - `junit.jupiter.execution.timeout.mode`
  - `junit.jupiter.execution.timeout.thread.mode.default`
  - `junit.jupiter.extensions.testinstantiation.extensioncontextscope.default`
  - `junit.jupiter.tempdir.cleanup.mode.default`
  - `junit.jupiter.testinstance.lifecycle.default`
* For consistency with test methods, `@Nested` classes declared in the same enclosing
  class or interface are now ordered in a deterministic but intentionally nonobvious
  way.
* `MediaType.APPLICATION_JSON_UTF_8` is now deprecated in favor of using
  `MediaType.APPLICATION_JSON`, since the industry considers UTF-8 to be the implicit
  default encoding for the `application/json` media type.
* `org.junit.jupiter.api.extension.MediaType` is now deprecated in favor of the new
  `org.junit.jupiter.api.MediaType`.
* The `publishFile(...)` methods in `TestReporter` which accept an
  `org.junit.jupiter.api.extension.MediaType` are now deprecated in favor of new variants
  which accept an `org.junit.jupiter.api.MediaType`.
* The `publishFile(...)` method in `ExtensionContext` which accepts an
  `org.junit.jupiter.api.extension.MediaType` is now deprecated in favor of a new variant
  which accepts an `org.junit.jupiter.api.MediaType`.
* `org.junit.jupiter.params.support.ParameterInfo` is now deprecated in favor of the new
  `org.junit.jupiter.params.ParameterInfo`.

[[release-notes-6.0.0-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Kotlin's `suspend` modifier may now be applied to test and lifecycle methods.
* The `Arguments` interface for parameterized tests is now officially a
  `@FunctionalInterface`.
* The implementation of `@CsvSource` and `@CsvFileSource` has been migrated from the no
  longer maintained https://github.com/uniVocity/univocity-parsers[univocity-parsers] to
  https://fastcsv.org/[FastCSV]. This improves the consistency of CSV input handling,
  including for malformed entries, and provides better error reporting and overall
  performance.
* Display names for `@ParameterizedClass` and `@ParameterizedTest` now consistently style
  name-value pairs for arguments using `name = value` formatting – for example,
  `fruit{nbsp}={nbsp}apple` instead of `fruit=apple`.
* Reason strings supplied to `ConditionEvaluationResult` APIs are now officially declared
  as `@Nullable`.
* Introduce `computeIfAbsent(...)` methods in `ExtensionContext.Store` to simplify working
  with non-nullable types.
* Text-based arguments in display names for parameterized tests are now quoted by default.
  In addition, special characters are escaped within quoted text. Please refer to the
  <<../user-guide/index.adoc#writing-tests-parameterized-tests-display-names-quoted-text,
  User Guide>> for details.
* <<../user-guide/index.adoc#writing-tests-parameterized-tests-argument-conversion-implicit-fallback,
  Fallback String-to-Object Conversion>> for parameterized tests now supports factory
  methods and factory constructors that accept a single `CharSequence` argument in
  addition to the existing support for factories that accept a single `String` argument.
* Non-printable control characters in display names are now replaced with alternative
  representations. Please refer to the
  <<../user-guide/index.adoc#writing-tests-display-names, User Guide>> for details.
* For consistency with `@TestClassOrder`, `@TestMethodOrder` annotations specified on a
  test class are now inherited by its `@Nested` inner classes, recursively.
* Introduce `MethodOrderer.Default` and `ClassOrderer.Default` for reverting back to
  default ordering on a `@Nested` class and its `@Nested` inner classes when an enclosing
  class specifies a different orderer via `@TestMethodOrder` or `@TestClassOrder`,
  respectively.
* `MediaType` now strips leading and trailing whitespace from a supplied `value`, `type`,
  or `subtype`.
* `MediaType` now eagerly rejects a _blank_ `value`, `type`, or `subtype`.


[[release-notes-6.0.0-junit-vintage]]
=== JUnit Vintage

[[release-notes-6.0.0-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-6.0.0-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* The JUnit Vintage engine is now deprecated and will report an INFO level discovery issue
  when it finds at least one JUnit 4 test class. For now, the intent of the deprecation is
  not to signal removal in the next major version but to clarify the intended purpose of
  the engine. It should only be used temporarily while migrating tests to JUnit Jupiter or
  another testing framework with native JUnit Platform support.

[[release-notes-6.0.0-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* Provide cancellation support for the Vintage test engine.
