[[release-notes-6.1.0-M1]]
== 6.1.0-M1

*Date of Release:* ❓

*Scope:* ❓

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/104?closed=1+[6.1.0-M1] milestone page in the JUnit
repository on GitHub.


[[release-notes-6.1.0-M1-junit-platform]]
=== JUnit Platform

[[release-notes-6.1.0-M1-junit-platform-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-6.1.0-M1-junit-platform-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* Deprecate constructors for `ForkJoinPoolHierarchicalTestExecutorService` in favor of the
  new `ParallelHierarchicalTestExecutorServiceFactory` that also supports
  `WorkerThreadPoolHierarchicalTestExecutorService`.

[[release-notes-6.1.0-M1-junit-platform-new-features-and-improvements]]
==== New Features and Improvements

* Support for creating a `ModuleSelector` from a `java.lang.Module` and using
  its classloader for test discovery.
* New `WorkerThreadPoolHierarchicalTestExecutorService` implementation used for parallel
  test execution that is backed by a regular thread pool rather than a `ForkJoinPool`.
  Engine authors should switch to use `ParallelHierarchicalTestExecutorServiceFactory`
  rather than instantiating a concrete `HierarchicalTestExecutorService` implementation
  for parallel execution directly.
* `OpenTestReportGeneratingListener` now supports redirecting XML events to a socket via
  the new `junit.platform.reporting.open.xml.socket` configuration parameter. When set to a
  port number, events are sent to `127.0.0.1:<port>` instead of being written to a file.
* Allow implementations of `HierarchicalTestEngine` to specify which nodes require the
  global read lock by overriding the `Node.isGlobalReadLockRequired()` method to return
  `false`.


[[release-notes-6.1.0-M1-junit-jupiter]]
=== JUnit Jupiter

[[release-notes-6.1.0-M1-junit-jupiter-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-6.1.0-M1-junit-jupiter-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-6.1.0-M1-junit-jupiter-new-features-and-improvements]]
==== New Features and Improvements

* Introduce new `dynamicTest(Consumer<? super Configuration>)` factory method for dynamic
  tests. It allows configuring the `ExecutionMode` of the dynamic test in addition to its
  display name, test source URI, and executable.
* Introduce new `dynamicContainer(Consumer<? super Configuration>)` factory method for
  dynamic containers. It allows configuring the `ExecutionMode` of the dynamic container
  and/or its children in addition to its display name, test source URI, and children.
* Enrich `assertInstanceOf` failure using the test subject `Throwable` as cause. It
  results in the stack trace of the test subject `Throwable` to get reported along with
  the failure.
* Make implementation of `HierarchicalTestExecutorService` used for parallel test
  execution configurable via the new
  `junit.jupiter.execution.parallel.config.executor-service` configuration parameter to
  in order to add support for `WorkerThreadPoolHierarchicalTestExecutorService`. Please
  refer to the
  <<../user-guide/index.adoc#writing-tests-parallel-execution-config-executor-service, User Guide>>
  for details.

[[release-notes-6.1.0-M1-junit-vintage]]
=== JUnit Vintage

[[release-notes-6.1.0-M1-junit-vintage-bug-fixes]]
==== Bug Fixes

* ❓

[[release-notes-6.1.0-M1-junit-vintage-deprecations-and-breaking-changes]]
==== Deprecations and Breaking Changes

* ❓

[[release-notes-6.1.0-M1-junit-vintage-new-features-and-improvements]]
==== New Features and Improvements

* ❓
