name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
inputs:
  distribution:
    required: true
    description: 'The JDK distribution to use'
    default: 'temurin'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: 17
        check-latest: true
    - shell: bash
      run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV # zizmor: ignore[github-env]
