import junitbuild.exec.CaptureJavaExecOutput
import junitbuild.exec.ClasspathSystemPropertyProvider
import junitbuild.exec.GenerateStandaloneConsoleLauncherShadowedArtifactsFile
import junitbuild.exec.RunConsoleLauncher
import junitbuild.extensions.isSnapshot
import junitbuild.extensions.javaModuleName
import junitbuild.extensions.mavenizedProjects
import junitbuild.extensions.modularProjects
import junitbuild.javadoc.GenerateJavadoc
import junitbuild.javadoc.VersionNumber
import junitbuild.javadoc.addStylesheet
import junitbuild.javadoc.linkOffline
import junitbuild.javadoc.moduleSourcePath
import junitbuild.javadoc.overview
import junitbuild.javadoc.since
import junitbuild.metadata.buildMetadata
import org.gradle.api.tasks.PathSensitivity.RELATIVE
import java.nio.file.Files
import kotlin.io.path.writeLines

plugins {
	alias(libs.plugins.plantuml)
	id("junitbuild.antora-conventions")
	id("junitbuild.build-parameters")
	id("junitbuild.kotlin-library-conventions")
	id("junitbuild.testing-conventions")
}

javaLibrary {
	mainJavaVersion = JavaVersion.VERSION_17
	testJavaVersion = JavaVersion.VERSION_17
}

val apiReport = configurations.dependencyScope("apiReport")
val apiReportClasspath = configurations.resolvable("apiReportClasspath") {
	extendsFrom(apiReport.get())
}
val standaloneConsoleLauncher = configurations.dependencyScope("standaloneConsoleLauncher")
val standaloneConsoleLauncherClasspath = configurations.resolvable("standaloneConsoleLauncherClasspath") {
	extendsFrom(standaloneConsoleLauncher.get())
}
val attestation = configurations.dependencyScope("attestation")
val attestationClasspath = configurations.resolvable("attestationClasspath") {
	extendsFrom(attestation.get())
	isTransitive = false
}
val javadocSource = configurations.dependencyScope("javadocSource")
val allJavadocSinceValuesClasspath = configurations.resolvable("allJavadocSinceValuesClasspath") {
	extendsFrom(javadocSource.get())
	attributes {
		attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, named("javadoc-since-values"))
	}
}
val javadocSourcePath = configurations.resolvable("javadocSourcePath") {
	extendsFrom(javadocSource.get())
	isTransitive = false
	attributes {
		attribute(Category.CATEGORY_ATTRIBUTE, named(Category.VERIFICATION))
		attribute(VerificationType.VERIFICATION_TYPE_ATTRIBUTE, named(VerificationType.MAIN_SOURCES))
	}
}
val javadocClasspath = configurations.dependencyScope("javadocClasspath")
val javadocApiClasspath = configurations.resolvable("javadocApiClasspath") {
	extendsFrom(javadocClasspath.get())
	attributes {
		attribute(Usage.USAGE_ATTRIBUTE, named(Usage.JAVA_API))
		attribute(Category.CATEGORY_ATTRIBUTE, named(Category.LIBRARY))
		attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, named(LibraryElements.JAR))
		attribute(Bundling.BUNDLING_ATTRIBUTE, named(Bundling.EXTERNAL))
	}
}
val javadocRuntimeClasspath = configurations.resolvable("javadocRuntimeClasspath") {
	extendsFrom(javadocClasspath.get())
	attributes {
		attribute(Usage.USAGE_ATTRIBUTE, named(Usage.JAVA_RUNTIME))
		attribute(Category.CATEGORY_ATTRIBUTE, named(Category.LIBRARY))
		attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, named(LibraryElements.JAR))
		attribute(Bundling.BUNDLING_ATTRIBUTE, named(Bundling.EXTERNAL))
	}
}
val tools = sourceSets.create("tools")
val toolsImplementation = configurations[tools.implementationConfigurationName]

dependencies {
	implementation(projects.junitJupiterApi) {
		because("Jupiter API is used in src/main/java")
	}

	compileOnlyApi(libs.jspecify)

	// Pull in all "modular projects" to ensure that they are included
	// in reports generated by the ApiReportGenerator.
	modularProjects.forEach { apiReport(it) }
	apiReport(libs.openTestReporting.tooling.spi)

	modularProjects.forEach {
		javadocSource(it)
		javadocClasspath(it)
	}
	javadocClasspath(libs.picocli)
	javadocClasspath(libs.fastcsv)
	javadocClasspath(libs.openTestReporting.events)
	javadocClasspath(libs.kotlinx.coroutines.core)
	javadocClasspath(kotlin("stdlib"))
	javadocClasspath(kotlin("reflect"))

	// Pull in all "mavenized projects" to ensure that they are included
	// in the generation of build provenance attestation.
	mavenizedProjects.forEach { attestation(it) }

	testImplementation(projects.junitJupiterMigrationsupport)
	testImplementation(projects.junitPlatformConsole)
	testImplementation(projects.junitPlatformSuite)
	testImplementation(projects.junitPlatformTestkit)
	testImplementation(projects.junitVintageEngine)
	testImplementation(kotlin("stdlib"))
	testImplementation(libs.kotlinx.coroutines.test)
	testRuntimeOnly(kotlin("reflect"))

	toolsImplementation(projects.junitPlatformCommons)
	toolsImplementation(libs.classgraph)
	toolsImplementation(libs.apiguardian)

	testImplementation(libs.jimfs) {
		because("Jimfs is used in src/test/java")
	}

	standaloneConsoleLauncher(projects.junitPlatformConsoleStandalone)
}

val snapshot = version.isSnapshot()
val releaseBranch = if (snapshot) "HEAD" else "r${version}"
val replaceCurrentDocs = buildParameters.documentation.replaceCurrentDocs
val ota4jDocVersion = libs.versions.opentest4j.map { if (it.isSnapshot()) "snapshot" else it }.get()
val apiGuardianDocVersion = libs.versions.apiguardian.map { if (it.isSnapshot()) "snapshot" else it }.get()

val generatedAsciiDocPath = layout.buildDirectory.dir("generated/asciidoc")
val consoleLauncherOptionsFile = generatedAsciiDocPath.map { it.file("console-launcher-options.txt") }
val consoleLauncherDiscoverOptionsFile = generatedAsciiDocPath.map { it.file("console-launcher-discover-options.txt") }
val consoleLauncherExecuteOptionsFile = generatedAsciiDocPath.map { it.file("console-launcher-execute-options.txt") }
val consoleLauncherEnginesOptionsFile = generatedAsciiDocPath.map { it.file("console-launcher-engines-options.txt") }
val experimentalApisTableFile = generatedAsciiDocPath.map { it.file("experimental-apis-table.adoc") }
val deprecatedApisTableFile = generatedAsciiDocPath.map { it.file("deprecated-apis-table.adoc") }
val standaloneConsoleLauncherShadowedArtifactsFile = generatedAsciiDocPath.map { it.file("console-launcher-standalone-shadowed-artifacts.adoc") }

val jdkJavadocBaseUrl = "https://docs.oracle.com/en/java/javase/${JavaVersion.current().majorVersion}/docs/api"
val elementListsDir = layout.buildDirectory.dir("elementLists")
val externalModulesWithoutModularJavadoc = mapOf(
		"org.apiguardian.api" to "https://apiguardian-team.github.io/apiguardian/docs/$apiGuardianDocVersion/api/",
		"org.assertj.core" to "https://javadoc.io/doc/org.assertj/assertj-core/${libs.versions.assertj.get()}/",
		"org.opentest4j" to "https://ota4j-team.github.io/opentest4j/docs/$ota4jDocVersion/api/",
		"org.jspecify" to "https://jspecify.dev/docs/api/",
)
require(externalModulesWithoutModularJavadoc.values.all { it.endsWith("/") }) {
	"all base URLs must end with a trailing slash: $externalModulesWithoutModularJavadoc"
}
val aggregatedJavadocSinceValuesFile = layout.buildDirectory.file("docs/aggregated-javadoc-since-values.txt")

spotless {
	format("asciidoctor") {
		target("modules/**/*.adoc")
		trimTrailingWhitespace()
		endWithNewline()
	}
}

tasks {

	val consoleLauncherTestReportsDir = project.layout.buildDirectory.dir("console-launcher-test-results")
	val consoleLauncherTestEventXmlFiles =
		files(consoleLauncherTestReportsDir.map { it.asFileTree.matching { include("**/open-test-report.xml") } })

	val consoleLauncherTest = register("consoleLauncherTest", RunConsoleLauncher::class) {
		args.addAll("execute")
		args.addAll("--scan-classpath")
		args.addAll("--config=junit.platform.reporting.open.xml.enabled=true")
		args.addAll("--config=junit.platform.reporting.open.xml.git.enabled=true")
		args.addAll("--config=junit.platform.output.capture.stdout=true")
		args.addAll("--config=junit.platform.output.capture.stderr=true")
		args.addAll("--config=junit.platform.discovery.issue.severity.critical=warning")
		outputs.dir(consoleLauncherTestReportsDir)
		argumentProviders.add(CommandLineArgumentProvider {
			listOf(
				"--reports-dir=${consoleLauncherTestReportsDir.get()}",
			)
		})
		args.addAll("--include-classname", ".*Tests")
		args.addAll("--include-classname", ".*Demo")
		args.addAll("--exclude-tag", "exclude")
		args.addAll("--exclude-tag", "timeout")

		doFirst {
			consoleLauncherTestReportsDir.get().asFile.deleteRecursively()
		}

		finalizedBy(generateOpenTestHtmlReport)
	}

	generateOpenTestHtmlReport {
		mustRunAfter(consoleLauncherTest)
		inputs.files(consoleLauncherTestEventXmlFiles).withPathSensitivity(RELATIVE).skipWhenEmpty()
		argumentProviders += CommandLineArgumentProvider {
			consoleLauncherTestEventXmlFiles.files.map { it.absolutePath }.toList()
		}
	}

	register<RunConsoleLauncher>("consoleLauncher") {
		hideOutput = false
		outputs.upToDateWhen { false }
	}

	test {
		include("**/*Demo.class")
		(options as JUnitPlatformOptions).apply {
			includeEngines("junit-vintage")
			includeTags("timeout")
			systemProperty("junit.platform.discovery.issue.severity.critical", "warning")
		}
	}

	check {
		dependsOn(consoleLauncherTest)
	}

	named<JavaCompile>(tools.compileJavaTaskName) {
		options.release.set(25)
	}

	named<Checkstyle>("checkstyleTools") {
		config = resources.text.fromFile(checkstyle.configDirectory.file("checkstyleMain.xml"))
	}

	val generateConsoleLauncherOptions = register("generateConsoleLauncherOptions", CaptureJavaExecOutput::class) {
		classpath.from(standaloneConsoleLauncherClasspath)
		mainClass = "org.junit.platform.console.ConsoleLauncher"
		args.addAll("--help", "--disable-banner")
		outputFile = consoleLauncherOptionsFile
	}

	val generateConsoleLauncherDiscoverOptions = register("generateConsoleLauncherDiscoverOptions", CaptureJavaExecOutput::class) {
		classpath.from(standaloneConsoleLauncherClasspath)
		mainClass = "org.junit.platform.console.ConsoleLauncher"
		args.addAll("discover", "--help", "--disable-banner")
		outputFile = consoleLauncherDiscoverOptionsFile
	}

	val generateConsoleLauncherExecuteOptions = register("generateConsoleLauncherExecuteOptions", CaptureJavaExecOutput::class) {
		classpath.from(standaloneConsoleLauncherClasspath)
		mainClass = "org.junit.platform.console.ConsoleLauncher"
		args.addAll("execute", "--help", "--disable-banner")
		outputFile = consoleLauncherExecuteOptionsFile
	}

	val generateConsoleLauncherEnginesOptions = register("generateConsoleLauncherEnginesOptions", CaptureJavaExecOutput::class) {
		classpath.from(standaloneConsoleLauncherClasspath)
		mainClass = "org.junit.platform.console.ConsoleLauncher"
		args.addAll("engines", "--help", "--disable-banner")
		outputFile = consoleLauncherEnginesOptionsFile
	}

	val generateApiTables = register("generateApiTables", JavaExec::class) {
		classpath = tools.runtimeClasspath
		mainClass = "org.junit.api.tools.ApiReportGenerator"
		systemProperty("api.moduleNames", modularProjects.map { it.javaModuleName }.sorted().joinToString(","))
		jvmArgumentProviders += ClasspathSystemPropertyProvider("api.modulePath", apiReportClasspath.get())
		val deprecationFile = deprecatedApisTableFile
		val experimentalFile = experimentalApisTableFile
		argumentProviders += CommandLineArgumentProvider {
			listOf(
				"DEPRECATED=${deprecationFile.get().asFile.absolutePath}",
				"EXPERIMENTAL=${experimentalFile.get().asFile.absolutePath}",
			)
		}
		outputs.cacheIf { true }
		outputs.file(deprecationFile)
		outputs.file(experimentalFile)
	}

	val generateStandaloneConsoleLauncherShadowedArtifactsFile = register("generateStandaloneConsoleLauncherShadowedArtifactsFile", GenerateStandaloneConsoleLauncherShadowedArtifactsFile::class) {
		inputJar.fileProvider(standaloneConsoleLauncherClasspath.flatMap { it.elements.map { it.single().asFile } })
		outputFile = standaloneConsoleLauncherShadowedArtifactsFile
	}

	plantUml {
		fileFormat = "SVG"
		outputs.cacheIf { true }
	}

	val plantUmlOutputDirectory = plantUml.flatMap { it.outputDirectory }

	val generateAsciidocInputs = register("generateAsciidocInputs") {
		dependsOn(
			generateConsoleLauncherOptions,
			generateConsoleLauncherDiscoverOptions,
			generateConsoleLauncherExecuteOptions,
			generateConsoleLauncherEnginesOptions,
			generateApiTables,
			generateStandaloneConsoleLauncherShadowedArtifactsFile,
			plantUmlOutputDirectory
		)
	}

	val downloadJavadocElementLists = register("downloadJavadocElementLists") {
		outputs.cacheIf { true }

		val targetDir = elementListsDir
		outputs.dir(targetDir).withPropertyName("targetDir")

		val modules = externalModulesWithoutModularJavadoc
		inputs.property("modules", modules)

		val textResourceFactory = resources.text

		doFirst {
			modules.forEach { (moduleName, baseUrl) ->
				val resource = textResourceFactory.fromUri("${baseUrl}element-list")
				targetDir.get().asFile.resolve(moduleName).apply {
					mkdir()
					resolve("element-list").writeText("module:$moduleName\n${resource.asString()}")
				}
			}
		}
	}

	val mergeJavadocSinceValues = register("mergeJavadocSinceValues") {

		val classpath = files(allJavadocSinceValuesClasspath.flatMap { it.elements })
		inputs.files(classpath).withPathSensitivity(PathSensitivity.NONE)

		val outputFile = aggregatedJavadocSinceValuesFile
		outputs.file(outputFile)

		outputs.cacheIf { true }

		doFirst {
			val initialVersions = setOf("1.0", "4.12", "5.0")
			val noPublicItems = setOf("1.3.1", "5.0.3", "5.4.1", "5.11.3")
			val excludes = initialVersions + noPublicItems
			val values = classpath.files.asSequence()
				.flatMap { it.readLines().asSequence() }
				.filter { it.isNotBlank() && it !in excludes }
				.sortedBy { VersionNumber(it) }
				.distinct()
			with(outputFile.get().asFile.toPath()) {
				Files.createDirectories(parent)
				writeLines(values)
			}
		}
	}

	val aggregateJavadocs = register("aggregateJavadocs", GenerateJavadoc::class) {
		dependsOn(downloadJavadocElementLists, mergeJavadocSinceValues)

		group = "Documentation"
		description = "Generates aggregated Javadocs"

		overview(layout.projectDirectory.file("src/javadoc/junit-overview.html"))
		addStylesheet(layout.projectDirectory.file("src/javadoc/junit-stylesheet.css"))
		since(aggregatedJavadocSinceValuesFile)

		jvmArgs.add("-Xmx1g")

		val title = "JUnit $version API"
		args.addAll(
				"-locale", "en", // must be the first option
				"-encoding", "UTF-8",
				"-quiet",
				"-doctitle", title,
				"-windowtitle", title,
				"-header", "JUnit",
				"-protected",
				"-splitindex",
				"-Xdoclint:all,-missing",
				"-Werror",
				"-html5",
				"-tag", "apiNote:a:API Note:",
				"-tag", "implNote:a:Implementation Note:",
				"-link", jdkJavadocBaseUrl,
				"-link", "https://junit.org/junit4/javadoc/${libs.versions.junit4.get()}/",
				"-group", "Jupiter", "org.junit.jupiter*",
				"-group", "Vintage", "org.junit.vintage*",
				"-group", "Platform", "org.junit.platform*",
				"--no-fonts",
				"-use",
				"-notimestamp",
		)

		externalModulesWithoutModularJavadoc.forEach { (moduleName, baseUrl) ->
			linkOffline(baseUrl, elementListsDir.map { it.dir(moduleName) })
		}

		modularProjects.forEach { project ->
			moduleSourcePath(
					project.javaModuleName,
					javadocSourcePath.get().incoming.artifactView {
						componentFilter { it is ProjectComponentIdentifier && it.projectPath == project.path }
					}.files
			)
		}

		sourceFiles.from(javadocSourcePath.get().incoming.files.asFileTree.matching {
			include("**/*.java")
		})

		classpath.from(javadocApiClasspath, javadocRuntimeClasspath)

		args.addAll(
			"--module", modularProjects.joinToString(",") { it.javaModuleName },
			"--add-modules", "info.picocli,org.opentest4j.reporting.events,de.siegmar.fastcsv",
			"--add-reads", "org.junit.platform.console=info.picocli",
			"--add-reads", "org.junit.platform.reporting=org.opentest4j.reporting.events",
			"--add-reads", "org.junit.jupiter.params=de.siegmar.fastcsv",
		)

		outputDirectory = layout.buildDirectory.dir("docs/javadoc")
	}

	val fixJavadoc = register("fixJavadoc", Copy::class) {
		dependsOn(aggregateJavadocs)
		group = "Documentation"
		description = "Fix links to external API specs in the locally aggregated Javadoc HTML files"

		val inputDir = aggregateJavadocs.flatMap { it.outputDirectory }
		val modules = externalModulesWithoutModularJavadoc
		inputs.property("externalModulesWithoutModularJavadoc", modules)
		from(inputDir.map { it.file("element-list") }) {
			// For compatibility with pre JDK 10 versions of the Javadoc tool
			rename { "package-list" }
		}
		val targetUrl = provider { project.version.toString().replace("-SNAPSHOT", "") }
			.map { version ->
				if (buildParameters.ci)
					"https://docs.junit.org/$version"
				else
					project.antora.siteDir.get().asFile.toURI().resolve(version).toString()
			}
		from(inputDir) {
			filesMatching("**/*.html") {
				val favicon =
					"""
						<link rel="icon" type="image/png" href="https://junit.org/assets/img/junit-diamond.png">
						<link rel="icon" type="image/svg+xml" href="https://junit.org/assets/img/junit-diamond-adaptive.svg" sizes="any">
						""".trimIndent()

				filter { line ->
					var result = if (line.startsWith("<head>")) line.replace("<head>", "<head>$favicon") else line
					modules.forEach { (moduleName, baseUrl) ->
						result = result.replace("${baseUrl}$moduleName/", baseUrl)
					}

					result = result.replace("https://docs.junit.org/current", targetUrl.get())

					return@filter result
				}
			}
			filesMatching("**/stylesheet.css") {
				// Remove invalid import of `dejavu.css` due to `javadoc --no-fonts`
				filter { line -> if (line.startsWith("@import url('fonts/")) null else line }
			}
		}
		into(layout.buildDirectory.dir("docs/fixedJavadoc"))
	}

	register("prepareGitHubAttestation", Sync::class) {
		val buildRevision = project.buildMetadata.map { it.buildRevision.substring(0, 7) }
		from(attestationClasspath)
		into(layout.buildDirectory.dir("attestation"))
		rename { fileName ->
			"(.*)-SNAPSHOT.jar".toRegex().replace(fileName) {
				"${it.groupValues[1]}-SNAPSHOT+${buildRevision.get()}.jar"
			}
		}
	}

	generateAntoraYml {
		asciidocAttributes.putAll(provider {
			mapOf(
				"version" to project.version,
				"junit4-version" to libs.versions.junit4.get(),
				"apiguardian-version" to libs.versions.apiguardian.get(),
				"ota4j-version" to libs.versions.opentest4j.get(),
				"surefire-version" to libs.versions.surefire.get(),
				"release-branch" to releaseBranch,
				"jdk-javadoc-base-url" to jdkJavadocBaseUrl
			)
		})
	}

	generateAntoraResources {
		dependsOn(generateAsciidocInputs, fixJavadoc)
	}
}
