[[junit-platform-suite-engine]]
=== JUnit Platform Suite Engine

The Suite Engine supports the declarative selection and execution of tests from
_any_ test engine on the JUnit Platform using the <<launcher-api>>.

image::junit-platform-suite-engine-diagram.svg[role=text-center]

[[junit-platform-suite-engine-setup]]
==== Setup

In addition to the `junit-platform-suite-api` and `junit-platform-suite-engine` artifacts,
you need _at least one_ other test engine and its dependencies on the classpath. See
<<dependency-metadata>> for details regarding group IDs, artifact IDs, and versions.

[[junit-platform-suite-engine-setup-required-dependencies]]
===== Required Dependencies

* `junit-platform-suite-api` in _test_ scope: artifact containing annotations needed to
  configure a test suite
* `junit-platform-suite-engine` in _test runtime_ scope: implementation of the
  `TestEngine` API for declarative test suites

NOTE: Both of the required dependencies are aggregated in the `junit-platform-suite`
artifact which can be declared in _test_ scope instead of declaring explicit dependencies
on `junit-platform-suite-api` and `junit-platform-suite-engine`.

[[junit-platform-suite-engine-setup-transitive-dependencies]]
===== Transitive Dependencies

* `junit-platform-launcher` in _test_ scope
* `junit-platform-engine` in _test_ scope
* `junit-platform-commons` in _test_ scope
* `opentest4j` in _test_ scope

[[junit-platform-suite-engine-example]]
==== @Suite Example

By annotating a class with `@Suite` it is marked as a test suite on the JUnit Platform.
As seen in the following example, selector and filter annotations can then be used to
control the contents of the suite.

[source,java,indent=0]
----
include::{testDir}/example/SuiteDemo.java[tags=user_guide]
----

.Additional Configuration Options
NOTE: There are numerous configuration options for discovering and filtering tests in a
test suite. Please consult the Javadoc of the `{suite-api-package}` package for a full
list of supported annotations and further details.

==== @BeforeSuite and @AfterSuite

`@BeforeSuite` and `@AfterSuite` annotations can be used on methods inside a
`@Suite`-annotated class. They will be executed respectively before and after
all tests of the test suite.

[source,java,indent=0]
----
include::{testDir}/example/BeforeAndAfterSuiteDemo.java[tags=user_guide]
----

[[junit-platform-suite-engine-duplicate-test-execution]]
==== Duplicate test execution

Depending on the declared test selection, different suites may contain the same tests,
potentially with different configurations.
Moreover, tests in a suite are executed in addition to the tests executed by every other
test engine. This can result in the same tests being executed twice.

image::junit-platform-suite-engine-duplicate-test-execution-diagram.svg[role=text-center]

This can be prevented by configuring your build tool to only include the
`junit-platform-suite` engine. Or by using a naming pattern. For example, name all suites
`*Suite` and all tests `*Test` and configure your build tool to only include the former.

Alternatively, consider <<running-tests-tags, using tags>> to select specific groups of tests.
