name: CI

on:
  workflow_call:

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Install GraalVM
      uses: graalvm/setup-graalvm@bef4b0e916c7dd079bf60fb95d49139f67e32c5f # v1.5.3
      with:
        distribution: graalvm
        version: latest
        java-version: 21
    - name: Build
      uses: ./.github/actions/main-build
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        # Disable configuration cache due to https://github.com/diffplug/spotless/issues/2318
        arguments: >-
          :platform-tooling-support-tests:test
          build
          jacocoRootReport
          --no-configuration-cache
    - name: Upload to Codecov.io
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Build
      uses: ./.github/actions/main-build
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Build
      uses: ./.github/actions/main-build
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Install Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: Install Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: documentation/.tool-versions
    - name: Build Documentation
      uses: ./.github/actions/run-gradle
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        arguments: >-
          antora
          -Pantora.downloadNode=false
          -Dscan.tag.Documentation
