name: Reproducible build

on:
  workflow_call:

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Restore Gradle cache and display toolchains
      uses: ./.github/actions/run-gradle
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        # Disable configuration cache due to https://github.com/diffplug/spotless/issues/2318
        arguments: >-
          --quiet
          --no-configuration-cache
    - name: Build and compare checksums
      shell: bash
      run: ./.github/scripts/checkBuildReproducibility.sh
