name: Gradle Dependency Submission

on:
  push:
    branches:
      - main

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  dependency-submission:
    if: github.repository == 'junit-team/junit-framework'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        java-version: 25
        check-latest: true
    - name: Generate and submit dependency graph
      id: dependency-submission
      uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      continue-on-error: true
    - name: Generate and submit dependency graph (retry)
      if: steps.dependency-submission.outcome == 'failure'
      uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
