name: Gradle Dependency Submission

on:
  push:
    branches:
      - main

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  dependency-submission:
    if: github.repository == 'junit-team/junit-framework'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: temurin
        java-version: 25
        check-latest: true
    - name: Generate and submit dependency graph
      id: dependency-submission
      uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      continue-on-error: true
    - name: Generate and submit dependency graph (retry)
      if: steps.dependency-submission.outcome == 'failure'
      uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
