name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # Cancels in-progress runs only for pull requests
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Install GraalVM
      uses: graalvm/setup-graalvm@60c26726de13f8b90771df4bc1641a52a3159994 # v1.5.2
      with:
        distribution: graalvm
        version: latest
        java-version: 21
    - name: Build
      uses: ./.github/actions/main-build
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        # Disable configuration cache due to https://github.com/diffplug/spotless/issues/2318
        arguments: >-
          :platform-tooling-support-tests:test
          build
          jacocoRootReport
          --no-configuration-cache
    - name: Upload to Codecov.io
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Build
      uses: ./.github/actions/main-build
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Build
      uses: ./.github/actions/main-build
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  publish_artifacts:
    name: Publish Snapshot Artifacts
    needs: macOS
    runs-on: ubuntu-latest
    permissions:
      attestations: write # required for build provenance attestation
      id-token: write # required for build provenance attestation
    if: github.event_name == 'push' && github.repository == 'junit-team/junit-framework' && (startsWith(github.ref, 'refs/heads/releases/') || github.ref == 'refs/heads/main')
    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Publish
      uses: ./.github/actions/run-gradle
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        arguments: >-
          publishAllPublicationsToMavenCentralSnapshotsRepository -x check
          prepareGitHubAttestation
    - name: Generate build provenance attestations
      uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-path: documentation/build/attestation/*.jar

  build_documentation:
    name: Build Documentation
    needs: macOS
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Install Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: Install Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: documentation/.tool-versions
    - name: Build Documentation
      uses: ./.github/actions/run-gradle
      with:
        encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        arguments: >-
          antora
          -Pantora.downloadNode=false
          -Dscan.tag.Documentation

  deploy_documentation:
    name: Deploy Documentation
    needs: build_documentation
    if: github.event_name == 'push' && github.repository == 'junit-team/junit-framework' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-docs.yml
    permissions:
      actions: write
