[[v6.0.2]]
== 6.0.2

*Date of Release:* January 6, 2026

*Scope:* Bug fixes and enhancements since 6.0.1

For a complete list of all _closed_ issues and pull requests for this release, consult the
link:{junit-framework-repo}+/milestone/113?closed=1+[6.0.2] milestone page in the JUnit
repository on GitHub.


[[v6.0.2-junit-platform]]
=== JUnit Platform

[[v6.0.2-junit-platform-bug-fixes]]
==== Bug Fixes

* Make `ConsoleLauncher` compatible with JDK 26 by avoiding final field mutations.
* Enable recursive updates when using `NamespacedHierarchicalStore.computeIfAbsent(N, K, Function)`.
  This provides parity with the deprecated `NamespacedHierarchicalStore.getOrComputeIfAbsent(N, K, Function)`


[[v6.0.2-junit-jupiter]]
=== JUnit Jupiter

[[v6.0.2-junit-jupiter-bug-fixes]]
==== Bug Fixes

* Allow using `@ResourceLock` on classes annotated with `@ClassTemplate` (or
  `@ParameterizedClass`).
* Change API status of recommended method in `ArgumentsProvider` as well as
  `ParameterDeclaration(s)` as "maintained" rather than "experimental".


[[v6.0.2-junit-vintage]]
=== JUnit Vintage

No changes.
